import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";

const inter = Inter({subsets: ["vietnamese"]});

const myFont = localFont({
    src: [
        {
            path: './Roboto-Thin.ttf',
            weight: '100'
        },
        {
            path: './Roboto-Regular.ttf',
            weight: '400'
        }
    ],
    display: 'swap',
    variable: '--font-roboto'
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    const cookieStore = cookies()
    const sessionToken = cookieStore.get('sessionToken')
    // console.log('RootLayout', cookieStore.get('sessionToken'))
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`}>
        <Toaster />
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Header />
            <AppProvider initialSessionToken={sessionToken?.value}>
                {children}
            </AppProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
